import java.util.prefs.Preferences;

/*
 * Display3Options.java
 *
 * Created on Jul 29, 2010, 4:22:30 PM
 */

/**
 *
 * @author Ilan
 */
public class Display3Options extends javax.swing.JDialog {
	Display3Frame parent = null;

    /** Creates new form Display3Options
	 * @param parent
	 * @param modal */
    public Display3Options(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.parent = (Display3Frame) parent;
		init();
    }
	
	private void init() {
		Preferences prefer1 = parent.jPrefer;
		setLocationRelativeTo(parent);
		jCheckSmallCursor.setSelected(prefer1.getBoolean("small 3cursor", false));
		Integer pixels = prefer1.getInt("3cursor size", 10);
		jTextNumPix.setText(pixels.toString());
		setEnabled();
	}

	void setEnabled() {
		boolean enab1 = jCheckSmallCursor.isSelected();
		jTextNumPix.setEnabled(enab1);
	}

	void saveVals() {
		Preferences prefer1 = parent.jPrefer;
		prefer1.putBoolean("small 3cursor", jCheckSmallCursor.isSelected());
		prefer1.putInt("3cursor size", getCursorSize());
	}

	int getCursorSize() {
		int pixels = 0;
		String tmp = jTextNumPix.getText();
		if( !tmp.isEmpty()) pixels = Integer.parseInt(tmp);
		return pixels;
	}

	@Override
	public void dispose() {
		saveVals();
		super.dispose();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckSmallCursor = new javax.swing.JCheckBox();
        jTextNumPix = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");

        jCheckSmallCursor.setText("Limit cross hairs to:");
        jCheckSmallCursor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckSmallCursorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckSmallCursor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNumPix, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckSmallCursor)
                    .addComponent(jTextNumPix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jCheckSmallCursorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckSmallCursorActionPerformed
		setEnabled();
	}//GEN-LAST:event_jCheckSmallCursorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckSmallCursor;
    private javax.swing.JTextField jTextNumPix;
    // End of variables declaration//GEN-END:variables

}
