import ij.WindowManager;
import java.awt.Point;
import java.util.prefs.Preferences;

/**
 *
 * @author ilan
 */
public class Gaussian extends javax.swing.JDialog {

	/**
	 * Creates new form Gaussian
	 * @param parent
	 * @param modal
	 */
	public Gaussian(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		init(parent);
	}

	private void init(java.awt.Frame parent) {
		int x, y;
		parentPet = ((PetCtFrame)parent).getPetCtPanel1();
		Preferences prefer = parentPet.parent.jPrefer;
		x = prefer.getInt("gaussian x", -1);
		y = prefer.getInt("gaussian y", -1);
		if(x>=0 && y>=0) setLocation(x,y);
		Double sigmaGauss = parentPet.parent.sigmaGauss;
		if( parentPet.parent.isFWHM) jComboSigma.setSelectedIndex(1);
		jTextSigma.setText(sigmaGauss.toString());
		changeDisplayFlg(false);
		WindowManager.addWindow(this);
	}

	void changeDisplayFlg(boolean isExit) {
		JFijiPipe pip1 = parentPet.petPipe;
		PetCtFrame parFrm = parentPet.parent;
		boolean isDisp = jCheckDisplay.isSelected();
		if( isExit) isDisp = false;
		if(pip1 == null) return;
		Double sigma = getSigma();
		if( !parFrm.sigmaGauss.equals(sigma)) {
			pip1.data1.resetGauss();
			pip1.sigmaGauss = parFrm.sigmaGauss = sigma;
			Preferences prefer = parFrm.jPrefer;
			prefer.put("sigma Gauss", sigma.toString());
			pip1.isFWHM = parFrm.isFWHM = getIsFWHM();
			prefer.putBoolean("Gauss FWHM", parFrm.isFWHM);
		}
		pip1.useGauss = isDisp;
		pip1.dirtyFlg = true;	// 2 lines to force update
		pip1.corSrc = null;
		parentPet.repaintAll();
	}

	double getSigma() {
		double ret = ChoosePetCt.parseDouble(jTextSigma.getText());
		if( ret < 0.1) ret = 0.1;
		return ret;
	}
	
	boolean getIsFWHM() {
		return jComboSigma.getSelectedIndex() > 0;
	}

	@Override
	public void dispose() {
		changeDisplayFlg(true);
		WindowManager.removeWindow(this);
		Preferences prefer = parentPet.parent.jPrefer;
		Point pt1 = getLocation();
		prefer.putInt("gaussian x", pt1.x);
		prefer.putInt("gaussian y", pt1.y);
		super.dispose();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextSigma = new javax.swing.JTextField();
        jCheckDisplay = new javax.swing.JCheckBox();
        jComboSigma = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PET smooth");

        jTextSigma.setText("2.5");

        jCheckDisplay.setSelected(true);
        jCheckDisplay.setText("display");
        jCheckDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDisplayActionPerformed(evt);
            }
        });

        jComboSigma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sigma (mm)", "FWHM(mm)" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextSigma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckDisplay)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jCheckDisplay)
                .addComponent(jComboSigma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDisplayActionPerformed
		changeDisplayFlg(false);
    }//GEN-LAST:event_jCheckDisplayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckDisplay;
    private javax.swing.JComboBox jComboSigma;
    private javax.swing.JTextField jTextSigma;
    // End of variables declaration//GEN-END:variables
	PetCtPanel parentPet = null;
}
