import javax.swing.SpinnerNumberModel;

/*
 * ModifyTable.java
 *
 * Created on Dec 1, 2024, 2:22 PM
 */
/**
 *
 * @author ilan
 */
public class ModifyTable extends javax.swing.JDialog {
	PetCtFrame parent = null;
	ManualSync manS = null;
	PetCtPanel panel1 = null;
	JFijiPipe setPipe = null;

	/**
	 * Creates new form ModifyTable
	 * @param parent
	 * @param modal
	 */
	public ModifyTable(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		this.parent = (PetCtFrame) parent;
		initComponents();
	}
	
	void init(ManualSync ms) {
		manS = ms;
		setLocation(ms.getLocation());
		panel1 = parent.getPetCtPanel1();
		setXY();
	}

	void offsetChanged(int indx) {
		switch (indx) {
			case 1:
				setCurrSpin(jSpinnerX, JFijiPipe.OFFTBLX);
				break;

			case 2:
				setCurrSpin(jSpinnerY, JFijiPipe.OFFTBLY);
				break;
		}
		parent.repaint();
	}

	private int setCurrSpin(javax.swing.JSpinner cur1, int type) {
		int i, wid2 = setPipe.mri1.getWid2();
		SpinnerNumberModel spin1 = (SpinnerNumberModel) cur1.getModel();
		i = spin1.getNumber().intValue();
		if( type == JFijiPipe.OFFTBLX || type == JFijiPipe.OFFTBLY) {
			if( i < -wid2 || i > wid2) {
				if( i < 0) i = -wid2;
				else i = wid2;
				cur1.setValue(i);
			}
		}
		setPipe.mri1.setBegin(type, i);
		return i;
	}

	private  void setXY() {
		setPipe = panel1.getMriOrCtPipe();
		JFijiPipe.mriOff m1 = setPipe.mri1;
		jSpinnerX.setValue(m1.getBegin(JFijiPipe.OFFTBLX));
		jSpinnerY.setValue(m1.getBegin(JFijiPipe.OFFTBLY));
//		isInit = false;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerX = new javax.swing.JSpinner();
        jSpinnerY = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify Table X,Y");

        jLabel1.setText("This allows you to modify the Table X,Y settings.");

        jLabel2.setText("It should be used with the Coronal display.");

        jLabel3.setText("Only there both X and Y are directly used.");

        jSpinnerX.setToolTipText("X value");
        jSpinnerX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerXStateChanged(evt);
            }
        });

        jSpinnerY.setToolTipText("Y value");
        jSpinnerY.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerYStateChanged(evt);
            }
        });

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSpinnerXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerXStateChanged
		offsetChanged(1);
    }//GEN-LAST:event_jSpinnerXStateChanged

    private void jSpinnerYStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerYStateChanged
		offsetChanged(2);
    }//GEN-LAST:event_jSpinnerYStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinnerX;
    private javax.swing.JSpinner jSpinnerY;
    // End of variables declaration//GEN-END:variables
}
