
import java.awt.Point;
import java.io.File;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ilan
 */
public class NiftiUpdate extends javax.swing.JDialog {

	/**
	 * Creates new form NiftiUpdate
	 * @param parent
	 * @param modal
	 */
	public NiftiUpdate(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	boolean isUpdate(File flGrw, BrownFat parent) {
		GrwFl = flGrw;
		if( !parent.isDelete || !flGrw.exists()) return false;
		Point pt1 = parent.getLocation();
		setLocation(pt1);
		setVisible(true);
		return updateNow;
	}

	void UpdateNow() {
		updateNow = true;
		GrwFl.delete();
		dispose();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButYes = new javax.swing.JButton();
        jButNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recalcuate Grown ROIs");

        jLabel1.setText("ROIs have been deleted. This requires a recalcuation of");

        jLabel2.setText("grown ROIs. This is a lenghty calculation and it is");

        jLabel3.setText("preferable to do it once after all non accpetable");

        jLabel4.setText("ROIs have been deleted.  Recalcualte now?");

        jButYes.setText("Yes");
        jButYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButYesActionPerformed(evt);
            }
        });

        jButNo.setText("No, do it later");
        jButNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButYes)
                        .addGap(18, 18, 18)
                        .addComponent(jButNo)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButYes)
                    .addComponent(jButNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButYesActionPerformed
		UpdateNow();
    }//GEN-LAST:event_jButYesActionPerformed

    private void jButNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButNoActionPerformed
		dispose();
    }//GEN-LAST:event_jButNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButNo;
    private javax.swing.JButton jButYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
	boolean updateNow = false;
	File GrwFl = null;
}
