import ij.IJ;
import ij.Macro;
import java.util.prefs.Preferences;
import javax.swing.SwingUtilities;

/**
 *
 * @author ilan
 */
public class StartPetData extends javax.swing.JFrame {

	/**
	 * Creates new form StartPetData
	 * @param arg
	 */
	public StartPetData( String arg) {
		super();
		runArg = Macro.getOptions();
//		initComponents();
//		init1();
		isInitialized = false;
		SwingUtilities.invokeLater(new Runnable(){
			@Override
			public void run() {
				Thread.currentThread().setUncaughtExceptionHandler(new PetCtFrame.MyExceptionHandler());
				initComponents();
				init1();
				isInitialized = true;
			}
		});
	}

	void init1() {
		jPrefer = Preferences.userNodeForPackage(StartPetData.class);
		jPrefer = jPrefer.node("biplugins");
		int indx = jPrefer.getInt("start up reader", 0);
		isAuto = false;
		if( runArg != null && runArg.startsWith("default")) isAuto = true;
//		IJ.log("arg= "+runArg +", " +isAuto);
		buttonGrp = new javax.swing.ButtonGroup();
		buttonGrp.add(jRadCD);
		buttonGrp.add(jRadBiDb);
		buttonGrp.add(jRadNone);
		switch(indx) {
			case 0:
				jRadCD.setSelected(true);
				break;

			case 1:
				jRadBiDb.setSelected(true);
				break;

			case 2:
				jRadNone.setSelected(true);
				break;
		}
	}

	@Override
	public void dispose() {
		int indx = 2;	// do nothing
		String cmd = jPrefer.get("start Fiji with", "Read_CD");
		if( jRadCD.isSelected()) {
			indx = 0;
		}
		if( jRadBiDb.isSelected()) {
			cmd = "Read_BI_Studies";
			indx = 1;
		}
		if( isAuto) {
			if( indx < 2) IJ.runPlugIn(cmd, null);
		}
		else jPrefer.putInt("start up reader", indx);
		super.dispose(); //To change body of generated methods, choose Tools | Templates.
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrp = new javax.swing.ButtonGroup();
        jRadCD = new javax.swing.JRadioButton();
        jRadBiDb = new javax.swing.JRadioButton();
        jRadNone = new javax.swing.JRadioButton();
        jButOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Startup Program");

        jRadCD.setText("Read from CD");

        jRadBiDb.setText("Read BI Studies");

        jRadNone.setText("None");

        jButOK.setText("OK");
        jButOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadCD)
                    .addComponent(jRadBiDb)
                    .addComponent(jRadNone)
                    .addComponent(jButOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadCD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadBiDb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadNone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOKActionPerformed
		dispose();
    }//GEN-LAST:event_jButOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGrp;
    private javax.swing.JButton jButOK;
    private javax.swing.JRadioButton jRadBiDb;
    private javax.swing.JRadioButton jRadCD;
    private javax.swing.JRadioButton jRadNone;
    // End of variables declaration//GEN-END:variables
	Preferences jPrefer;
	boolean isAuto, isInitialized;
	String runArg;
}
